collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.7604539
  brandStrength: 0.4516649
  lightness: 0.5633214
  brandColors:
    - '#A19177'
    - '#40484B'
    - '#606058'
    - '#847964'
    - '#4D5050'
  rhythmicContrast: 0
typography_spectrum: 0
layout_spectrum: 0.3138548
name: nijube
