layout_spectrum: 0.3138548
typography_spectrum: 0.3289253
color:
  saturation: 0.8548144
  lightness: 0.4720878
  brandStrength: 0.8272636
  rhythmicContrast: 0.6715687
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
name: nijube
